### ISSUE TITLE
Empty lines are treated as having no indentation

### ISSUE THREAD

**Issue by ronandalton** [jessekelighine/vindent.vim#8]
Currently empty lines are treated as having no indentation. However, this can be an issue when you are on an empty line inside a function for example, and want to jump to the previous line with less indent. Currently this action doesn't work, so you need to move the cursor down to a line that is not empty and then issue the command again. It might be nice if the plugin could infer the indentation of the current line even when empty, and use it to do its movement and text-object calculations given that inferred indent.

Same issue in indentwise plugin: jeetsukumaran/vim-indentwise#16

**Comment by jessekelighine** [comment]
Two things:

1. I intentionally do not want to conflate "empty lines" and "lines with no indentation". Hence, do not want to compare the number returned by `indent()` directly. This is for the reason that "empty lines" often have special meanings. For example, consider the code
   ```vim
   1 function func1()
   2   return 1
   3 endfunction
   4 
   5 function func2()
   6   return 2
   7 endfunction
   ```
   I believe most people do not consider lines 3 to 5 to be in the same "text block", although they all have an indent value of 0 according to `indent()`. As a result, as you have already noticed, I have `s:compare` doing some logic *before* comparing the values returned by `indent()`. In fact, `s:compare` consider empty lines to have "negative indentation". That is, if the basis (`base` argument in `s:compare`) for comparison is an empty line, then only other empty lines are considered to have the same indentation, and every other non-empty lines are considered to have more indentation.
2. `vindent.vim` is designed to work *context-free*. That is, I purposefully do not want `vindent.vim` to infer the indentation of an empty line for two reasons:
	1. For `vindent.vim` to be *fully* context-aware, something like LSP would be necessary. I wrote `vindent.vim` with minimalism in mind, so using LSP is out of the question.
	2. I could implement something like `<SID>get_indent()` to "guess" the indentation level. However, this would lead to unintuitive (for me at least) results, especially in dealing with empty lines in situations similarly to the example given above.

For the above two points, I will not merge the pull request. Nevertheless, thanks for showing interesting in `vindent.vim` and trying to parsing my spaghetti code 😅

**Comment by ronandalton** [comment]
I personally think this would be a nice feature to have. I've adapted my code to fix that case you mentioned, and it now treats empty lines between code blocks as having an indent of -1. My implementation logic is based on the behavior of the [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) plugin which draws indentation guides for empty lines (that plugin also doesn't need LSP to do that). It may not be perfect, but it works in most cases and avoids the issue where trying to go to a previous indentation does nothing, and selecting everything in a block ends up selecting the entire file by accident. Perhaps you would consider adding an option to enable this functionality if you're not happy with it being on by default?

Anyway if you've already made up your mind on this then that's okay too. I just thought maybe this functionality might be helpful to others too. Regardless I wanted to say thank you for making this plugin, as I've found it a useful enhancement to the default vim experience.

**Comment by jessekelighine** [comment]
After some thought I now agree that inferring indentation of empty lines in most occasions are indeed possible. I implemented the functionality as an option on the branch `infer-indent`. Simply put `let g:vindent_infer = 1` in your `init.vim` (or `vim.g.vindent_begin = 1` in your `init.lua`) and you are good to go. Please test it out and tell me what you think!

**Comment by ronandalton** [comment]
This is great. Thanks so much for this!

I tested it out and it works quite well. However for languages such as Python that use indentation to define blocks of code, the strategy of taking the indent of the previous line may not always be optimal. I think what you want to be doing is always taking the indent of the next line unless it marks the end of a block, in which case take the previous line's indent. You can detect the end of a block using a regex like `"^\\s*\\(}\\|]\\|)\\|end\\)"`.

**Comment by jessekelighine** [comment]
Thanks for reporting back, glad you liked the update!

Could you provide an example of the intended behavior regarding the regex `'^\s*\(}\|]\|)\|end\)'`? I fail to see the problem with languages like Python under the current implementation.

**Comment by ronandalton** [comment]
Sure. Here is some example Python code to illustrate my point:

![image](https://github.com/jessekelighine/vindent.vim/assets/86718942/d115a242-aa42-437d-bf35-0387baa91b0e)

This screenshot shows the indentation guides a typical text editor will draw for blank lines (VSCode in this case but Neovim with the indent-blankline plugin shows the same).

With the current code, line 6 would get an indentation of 12 because it's taking the indentation from the previous line, and line 9 would get an indentation of 8 for the same reason. However, it may make more sense for these lines to be given indentation values of 4 and -1 respectively. This reflects how the indentation guides are shown and more closely matches what the inferred indents for the equivalent C code would have been (especially between functions where indent should be -1).

That's why I think it may be best to always take the indentation of the next line, and if it looks like it marks the end of a block (using the regex), use the indentation of the previous line instead. The slight downside to that is that lines before \#ifdef's in C won't be counted as indented, but that is a small price to pay I think for better supporting languages like Python (indent-blankline actually uses another regex just for C files to ignore preprocessor directives). It is also more likely that a user is executing a motion or selecting a text object from somewhere inside a block of C-style code and not right at the end of a block (where there probably shouldn't be any blank space anyway), so having a regex that matches every possible block end line isn't that important.

**Comment by jessekelighine** [comment]
I pushed a new commit to the branch `infer-indent`, I believe it now produces the intended behavior. I refrained from using regex since it is too ad hoc and language specific for my liking. Try it out!

**Comment by ronandalton** [comment]
If I'm not mistaken the behavior is identical to before? You still get the max of the two indents in the last line and the line you added before that appears redundant.

**Comment by ronandalton** [comment]
You could probably just simplify the function down to this if you don't want to use a regex:
```vim
function! <SID>get_indent(line, infer=g:vindent_infer)
	if !a:infer || !s:empty(a:line) | return s:indent(a:line) | endif
	let l:line_next = nextnonblank(a:line)
	if !s:valid(l:line_next) || indent(l:line_next)==0 | return -1 | endif
	return indent(l:line_next)
endfunction
```

**Comment by jessekelighine** [comment]
Ah yes, my bad. Now I fully understand your point. It seems like regex would be necessary. Let me think about whether to add this to `vindent.vim`.

**Comment by jessekelighine** [comment]
I added regex matching in the latest commit on [`infer-indent`](/jessekelighine/vindent.vim/tree/infer-indent) branch. You can set
```vim
let g:vindent_block_ending = [')', ']', '}', 'end', 'else', 'elif']
```
in your `init.vim`. If `g:vindent_infer` is set to `1` and `g:vindent_block_ending` is undefined, then `vindent.vim` will simply use the logic from 0ff63e2638f3946886a1cbc4ac86a25d9bc059d3 to infer indentation of empty lines; if `g:vindent_infer` is set to `1` and `g:vindent_block_ending` is defined, then the behavior should match your description.

**Comment by ronandalton** [comment]
There were still some logic issues with your implementation so I took the liberty of rewriting it to work the way we want. The logic in your last line wasn't being reached in some cases and the methods are different enough it's not easy to combine.

The following code has the correct logic to support both methods:
```vim
function! <SID>get_indent(line, infer=g:vindent_infer)
	if !a:infer || !s:empty(a:line) | return s:indent(a:line) | endif
	let l:line_prev = prevnonblank(a:line)
	let l:line_next = nextnonblank(a:line)
	if !s:valid(l:line_next) || !s:valid(l:line_prev) | return -1 | endif
	if !exists("g:vindent_block_ending")
		let l:indent = max([indent(l:line_prev), indent(l:line_next)])
		return l:indent==0 ? -1 : l:indent
	else
		if s:is_block_ending(l:line_next)
			return max([indent(l:line_next), min([indent(l:line_next)+shiftwidth(), indent(l:line_prev)])])
		else
			return indent(l:line_next)==0 ? -1 : indent(l:line_next)
		endif
	endif
endfunction
```
Please use this code unless you have any major objections to it. I've tested it relatively thoroughly and it works. If you change it then think carefully about if that changes the logic too. The only new logical change I made is improving the infer logic for the indent before a block end statement. `indent(l:line_prev)` is now clamped to a more reasonable range (helps for if statements without braces before a block end line).

**Comment by jessekelighine** [comment]
Looks good to me. I might change the logic a little bit regarding the case when `g:vindent_block_ending` is not defined to deal with edge cases when only one of `l:line_prev` or `l:line_next` is not valid. Maybe something like:
```vim
function! <SID>get_indent(line, infer=g:vindent_infer)
	if !a:infer || !s:empty(a:line) | return s:indent(a:line) | endif
	let l:line_prev = prevnonblank(a:line)
	let l:line_next = nextnonblank(a:line)
	if !exists("g:vindent_block_ending")
		if !s:valid(l:line_prev) && !s:valid(l:line_next) | return -1 | endif
		if !s:valid(l:line_prev) | return indent(l:line_next)==0 ? -1 : indent(l:line_next) | endif
		if !s:valid(l:line_next) | return indent(l:line_prev)==0 ? -1 : indent(l:line_prev) | endif
		let l:indent = max([indent(l:line_prev), indent(l:line_next)])
		return l:indent==0 ? -1 : l:indent
	else
		if !s:valid(l:line_next) || !s:valid(l:line_prev) | return -1 | endif
		if s:is_block_ending(l:line_next)
			return max([indent(l:line_next), min([indent(l:line_next)+shiftwidth(), indent(l:line_prev)])])
		else
			return indent(l:line_next)==0 ? -1 : indent(l:line_next)
		endif
	endif
endfunction
```

Nevertheless, I wouldn't change the part when `exists("g:vindent_block_ending")` is true.

If you don't mind, please make a new pull request with your code to the branch  [`infer-indent`](/jessekelighine/vindent.vim/tree/infer-indent) so your name will appear on the list of contributors. Thanks!

**Comment by ronandalton** [comment]
Cheers. I've made a pull request.
